runtime: python39  # ou qualquer outra runtime compatível

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: (.*\.html)

- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.css)
  static_files: \1
  upload: (.*\.css)

- url: /.*
  static_files: index.html
  upload: index.html
