#Status Licença
AGUARDANDO_PROCESSAMENTO = "AGUARDANDO_PROCESSAMENTO"
PROCESSADA = "PROCESSADA"
ERRO_PROCESSAMENTO = "ERRO_PROCESSAMENTO"

#Status Exigência
PENDENTE = "PENDENTE"
CUMPRIDA = "CUMPRIDA"