# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image (usando Dockerfile na pasta deploy)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'deploy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/ecosync-backend:$COMMIT_SHA', '..']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ecosync-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ecosync-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ecosync-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - |
        PORT=8080,
        ENVIRONMENT=production,
        FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET,
        ALLOWED_ORIGINS=$_ALLOWED_ORIGINS,
        PROJECT_ID=$PROJECT_ID,
        SERVICE_NAME=ecosync-backend

# Substitutions - configure estes valores no Cloud Build Trigger
substitutions:
  _FIREBASE_STORAGE_BUCKET: 'ecosync-project.appspot.com'
  _ALLOWED_ORIGINS: 'https://ecosync-frontend.web.app'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ecosync-backend:$COMMIT_SHA'

# Timeout for the entire build
timeout: '1200s'